-- 0002_seed_zwilling.sql
-- Idempotent seed of the 21 ZWILLING preset food groups + localized names +
-- shelf-life (storable) days. Generated from src/shelf_life.json. Mirrors the
-- JS seedPresets() routine in src/seed.ts so tests and deploys agree.

INSERT INTO foodgroups (cloud_id,bucket,owner_id,section,icon_name,position) VALUES ('4HD7ErEPKa5DJPlpjwEcIM','ZWILLING',NULL,'Meat','',0) ON CONFLICT(cloud_id) DO UPDATE SET section=excluded.section, icon_name=excluded.icon_name, position=excluded.position;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4HD7ErEPKa5DJPlpjwEcIM','cs','Beef (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4HD7ErEPKa5DJPlpjwEcIM','de','Rindfleisch (frisch)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4HD7ErEPKa5DJPlpjwEcIM','en','Beef (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4HD7ErEPKa5DJPlpjwEcIM','es','Vacuno (fresco)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4HD7ErEPKa5DJPlpjwEcIM','fr','Bœuf (frais)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4HD7ErEPKa5DJPlpjwEcIM','hu','Beef (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4HD7ErEPKa5DJPlpjwEcIM','it','Manzo (fresco)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4HD7ErEPKa5DJPlpjwEcIM','ja','牛肉（生）') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4HD7ErEPKa5DJPlpjwEcIM','ko','Beef (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4HD7ErEPKa5DJPlpjwEcIM','nl','Rundsvlees (vers)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4HD7ErEPKa5DJPlpjwEcIM','pl','Beef (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4HD7ErEPKa5DJPlpjwEcIM','pt','Carne de vaca (fresca)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4HD7ErEPKa5DJPlpjwEcIM','sk','Beef (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4HD7ErEPKa5DJPlpjwEcIM','tr','Biftek (taze)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4HD7ErEPKa5DJPlpjwEcIM','zh','Beef (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('4HD7ErEPKa5DJPlpjwEcIM','freezer','freezer',90) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('4HD7ErEPKa5DJPlpjwEcIM','fridge','fridge',8) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('4HD7ErEPKa5DJPlpjwEcIM','zerodegreezone','zerodegreezone',9) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;

INSERT INTO foodgroups (cloud_id,bucket,owner_id,section,icon_name,position) VALUES ('5951bLLppivKv13CLtc5Xf','ZWILLING',NULL,'Vegetables & Fruits','',0) ON CONFLICT(cloud_id) DO UPDATE SET section=excluded.section, icon_name=excluded.icon_name, position=excluded.position;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5951bLLppivKv13CLtc5Xf','cs','Vegetables (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5951bLLppivKv13CLtc5Xf','de','Gemüse (frisch)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5951bLLppivKv13CLtc5Xf','en','Vegetables (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5951bLLppivKv13CLtc5Xf','es','Verduras (frescas)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5951bLLppivKv13CLtc5Xf','fr','Légumes (frais)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5951bLLppivKv13CLtc5Xf','hu','Vegetables (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5951bLLppivKv13CLtc5Xf','it','Verdure (fresche)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5951bLLppivKv13CLtc5Xf','ja','野菜（生）') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5951bLLppivKv13CLtc5Xf','ko','Vegetables (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5951bLLppivKv13CLtc5Xf','nl','Groenten (vers)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5951bLLppivKv13CLtc5Xf','pl','Vegetables (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5951bLLppivKv13CLtc5Xf','pt','Vegetais (frescos)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5951bLLppivKv13CLtc5Xf','sk','Vegetables (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5951bLLppivKv13CLtc5Xf','tr','Sebzeler (taze)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5951bLLppivKv13CLtc5Xf','zh','Vegetables (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('5951bLLppivKv13CLtc5Xf','freezer','freezer',90) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('5951bLLppivKv13CLtc5Xf','fridge','fridge',20) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('5951bLLppivKv13CLtc5Xf','zerodegreezone','zerodegreezone',22) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;

INSERT INTO foodgroups (cloud_id,bucket,owner_id,section,icon_name,position) VALUES ('NCQizVdUaju362p0mci7j','ZWILLING',NULL,'Vegetables & Fruits','zwillingRapier/Herbs',0) ON CONFLICT(cloud_id) DO UPDATE SET section=excluded.section, icon_name=excluded.icon_name, position=excluded.position;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('NCQizVdUaju362p0mci7j','cs','Herbs (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('NCQizVdUaju362p0mci7j','de','Kräuter (frisch)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('NCQizVdUaju362p0mci7j','en','Herbs (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('NCQizVdUaju362p0mci7j','es','Hierbas (frescas)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('NCQizVdUaju362p0mci7j','fr','Herbes (fraîches)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('NCQizVdUaju362p0mci7j','hu','Herbs (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('NCQizVdUaju362p0mci7j','it','Erbe aromatiche (fresche)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('NCQizVdUaju362p0mci7j','ja','ハーブ（生）') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('NCQizVdUaju362p0mci7j','ko','Herbs (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('NCQizVdUaju362p0mci7j','nl','Kruiden (vers)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('NCQizVdUaju362p0mci7j','pl','Herbs (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('NCQizVdUaju362p0mci7j','pt','Ervas (frescas)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('NCQizVdUaju362p0mci7j','sk','Herbs (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('NCQizVdUaju362p0mci7j','tr','Otlar (taze)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('NCQizVdUaju362p0mci7j','zh','Herbs (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('NCQizVdUaju362p0mci7j','freezer','freezer',90) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('NCQizVdUaju362p0mci7j','fridge','fridge',10) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('NCQizVdUaju362p0mci7j','zerodegreezone','zerodegreezone',11) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;

INSERT INTO foodgroups (cloud_id,bucket,owner_id,section,icon_name,position) VALUES ('4VwL0PH4obFLRUSV9RDHVT','ZWILLING',NULL,'Fish & Seafood','',0) ON CONFLICT(cloud_id) DO UPDATE SET section=excluded.section, icon_name=excluded.icon_name, position=excluded.position;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4VwL0PH4obFLRUSV9RDHVT','cs','Seafood (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4VwL0PH4obFLRUSV9RDHVT','de','Meeresfrüchte (frisch)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4VwL0PH4obFLRUSV9RDHVT','en','Seafood (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4VwL0PH4obFLRUSV9RDHVT','es','Marisco (fresco)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4VwL0PH4obFLRUSV9RDHVT','fr','Fruits de mer (frais)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4VwL0PH4obFLRUSV9RDHVT','hu','Seafood (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4VwL0PH4obFLRUSV9RDHVT','it','Meeresfrüchte (frisch)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4VwL0PH4obFLRUSV9RDHVT','ja','シーフード（生）') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4VwL0PH4obFLRUSV9RDHVT','ko','Seafood (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4VwL0PH4obFLRUSV9RDHVT','nl','Fisk og skaldyr (friske)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4VwL0PH4obFLRUSV9RDHVT','pl','Seafood (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4VwL0PH4obFLRUSV9RDHVT','pt','Marisco (fresco)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4VwL0PH4obFLRUSV9RDHVT','sk','Seafood (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4VwL0PH4obFLRUSV9RDHVT','tr','Deniz Ürünleri (taze)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4VwL0PH4obFLRUSV9RDHVT','zh','Seafood (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('4VwL0PH4obFLRUSV9RDHVT','freezer','freezer',40) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('4VwL0PH4obFLRUSV9RDHVT','fridge','fridge',3) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('4VwL0PH4obFLRUSV9RDHVT','zerodegreezone','zerodegreezone',4) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;

INSERT INTO foodgroups (cloud_id,bucket,owner_id,section,icon_name,position) VALUES ('5BBd8tF63OavTkUvKWZbW5','ZWILLING',NULL,'Vegetables & Fruits','',0) ON CONFLICT(cloud_id) DO UPDATE SET section=excluded.section, icon_name=excluded.icon_name, position=excluded.position;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5BBd8tF63OavTkUvKWZbW5','cs','Lettuce (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5BBd8tF63OavTkUvKWZbW5','de','Blattsalate (frisch)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5BBd8tF63OavTkUvKWZbW5','en','Lettuce (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5BBd8tF63OavTkUvKWZbW5','es','Lechuga (fresca)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5BBd8tF63OavTkUvKWZbW5','fr','Laitue (fraîche)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5BBd8tF63OavTkUvKWZbW5','hu','Lettuce (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5BBd8tF63OavTkUvKWZbW5','it','Lattuga (fresca)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5BBd8tF63OavTkUvKWZbW5','ja','レタス（生）') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5BBd8tF63OavTkUvKWZbW5','ko','Lettuce (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5BBd8tF63OavTkUvKWZbW5','nl','Sla (vers)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5BBd8tF63OavTkUvKWZbW5','pl','Lettuce (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5BBd8tF63OavTkUvKWZbW5','pt','Alface (fresca)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5BBd8tF63OavTkUvKWZbW5','sk','Lettuce (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5BBd8tF63OavTkUvKWZbW5','tr','Marul (taze)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5BBd8tF63OavTkUvKWZbW5','zh','Lettuce (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('5BBd8tF63OavTkUvKWZbW5','fridge','fridge',10) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('5BBd8tF63OavTkUvKWZbW5','zerodegreezone','zerodegreezone',12) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;

INSERT INTO foodgroups (cloud_id,bucket,owner_id,section,icon_name,position) VALUES ('5otQ4qBgtoSZg03mYgD6Pg','ZWILLING',NULL,'Cereals','',0) ON CONFLICT(cloud_id) DO UPDATE SET section=excluded.section, icon_name=excluded.icon_name, position=excluded.position;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5otQ4qBgtoSZg03mYgD6Pg','cs','Pasta') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5otQ4qBgtoSZg03mYgD6Pg','de','Nudeln') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5otQ4qBgtoSZg03mYgD6Pg','en','Pasta') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5otQ4qBgtoSZg03mYgD6Pg','es','Pasta') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5otQ4qBgtoSZg03mYgD6Pg','fr','Pâtes') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5otQ4qBgtoSZg03mYgD6Pg','hu','Pasta') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5otQ4qBgtoSZg03mYgD6Pg','it','Pasta') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5otQ4qBgtoSZg03mYgD6Pg','ja','パスタ') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5otQ4qBgtoSZg03mYgD6Pg','ko','Pasta') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5otQ4qBgtoSZg03mYgD6Pg','nl','Pasta') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5otQ4qBgtoSZg03mYgD6Pg','pl','Pasta') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5otQ4qBgtoSZg03mYgD6Pg','pt','Massa') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5otQ4qBgtoSZg03mYgD6Pg','sk','Pasta') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5otQ4qBgtoSZg03mYgD6Pg','tr','Makarna') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('5otQ4qBgtoSZg03mYgD6Pg','zh','Pasta') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('5otQ4qBgtoSZg03mYgD6Pg','cupboard','cupboard',365) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;

INSERT INTO foodgroups (cloud_id,bucket,owner_id,section,icon_name,position) VALUES ('6YnLfZJikxpQfMEb8oe3vd','ZWILLING',NULL,'Cooked','',0) ON CONFLICT(cloud_id) DO UPDATE SET section=excluded.section, icon_name=excluded.icon_name, position=excluded.position;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6YnLfZJikxpQfMEb8oe3vd','cs','Cooked pasta and rice') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6YnLfZJikxpQfMEb8oe3vd','de','Gekochte Pasta und Reis') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6YnLfZJikxpQfMEb8oe3vd','en','Cooked pasta and rice') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6YnLfZJikxpQfMEb8oe3vd','es','Pasta y arroz cocidos') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6YnLfZJikxpQfMEb8oe3vd','fr','Pâtes et riz cuites') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6YnLfZJikxpQfMEb8oe3vd','hu','Cooked pasta and rice') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6YnLfZJikxpQfMEb8oe3vd','it','Pasta e riso cotti') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6YnLfZJikxpQfMEb8oe3vd','ja','ご飯、茹でた麺') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6YnLfZJikxpQfMEb8oe3vd','ko','Cooked pasta and rice') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6YnLfZJikxpQfMEb8oe3vd','nl','Gekookte pasta en rijst') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6YnLfZJikxpQfMEb8oe3vd','pl','Cooked pasta and rice') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6YnLfZJikxpQfMEb8oe3vd','pt','Massa cozida e arroz') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6YnLfZJikxpQfMEb8oe3vd','sk','Cooked pasta and rice') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6YnLfZJikxpQfMEb8oe3vd','tr','Pişmiş makarna ve pirinç') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6YnLfZJikxpQfMEb8oe3vd','zh','Cooked pasta and rice') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('6YnLfZJikxpQfMEb8oe3vd','freezer','freezer',30) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('6YnLfZJikxpQfMEb8oe3vd','fridge','fridge',7) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('6YnLfZJikxpQfMEb8oe3vd','zerodegreezone','zerodegreezone',9) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;

INSERT INTO foodgroups (cloud_id,bucket,owner_id,section,icon_name,position) VALUES ('7CncwIRfz1c7dognT2dq5B','ZWILLING',NULL,'Meat','',0) ON CONFLICT(cloud_id) DO UPDATE SET section=excluded.section, icon_name=excluded.icon_name, position=excluded.position;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7CncwIRfz1c7dognT2dq5B','cs','Pork (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7CncwIRfz1c7dognT2dq5B','de','Schweinefleisch (frisch)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7CncwIRfz1c7dognT2dq5B','en','Pork (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7CncwIRfz1c7dognT2dq5B','es','Cerdo (fresco)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7CncwIRfz1c7dognT2dq5B','fr','Porc (frais)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7CncwIRfz1c7dognT2dq5B','hu','Pork (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7CncwIRfz1c7dognT2dq5B','it','Maiale (fresco)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7CncwIRfz1c7dognT2dq5B','ja','豚肉（生）') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7CncwIRfz1c7dognT2dq5B','ko','Pork (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7CncwIRfz1c7dognT2dq5B','nl','Varkensvlees (vers)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7CncwIRfz1c7dognT2dq5B','pl','Pork (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7CncwIRfz1c7dognT2dq5B','pt','Carne de porco (fresca)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7CncwIRfz1c7dognT2dq5B','sk','Pork (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7CncwIRfz1c7dognT2dq5B','tr','Domuz Eti (taze)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7CncwIRfz1c7dognT2dq5B','zh','Pork (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('7CncwIRfz1c7dognT2dq5B','freezer','freezer',90) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('7CncwIRfz1c7dognT2dq5B','fridge','fridge',6) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('7CncwIRfz1c7dognT2dq5B','zerodegreezone','zerodegreezone',7) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;

INSERT INTO foodgroups (cloud_id,bucket,owner_id,section,icon_name,position) VALUES ('1K54WGNoqmr4w4inGjprAd','ZWILLING',NULL,'Meat','',0) ON CONFLICT(cloud_id) DO UPDATE SET section=excluded.section, icon_name=excluded.icon_name, position=excluded.position;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1K54WGNoqmr4w4inGjprAd','cs','Poultry (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1K54WGNoqmr4w4inGjprAd','de','Geflügel (frisch)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1K54WGNoqmr4w4inGjprAd','en','Poultry (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1K54WGNoqmr4w4inGjprAd','es','Aves (fresco)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1K54WGNoqmr4w4inGjprAd','fr','Volaille (fraîche)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1K54WGNoqmr4w4inGjprAd','hu','Poultry (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1K54WGNoqmr4w4inGjprAd','it','Pollame (fresco)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1K54WGNoqmr4w4inGjprAd','ja','鶏肉（生）') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1K54WGNoqmr4w4inGjprAd','ko','Poultry (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1K54WGNoqmr4w4inGjprAd','nl','Gevogelte (vers)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1K54WGNoqmr4w4inGjprAd','pl','Poultry (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1K54WGNoqmr4w4inGjprAd','pt','Aves de capoeira (frescas)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1K54WGNoqmr4w4inGjprAd','sk','Poultry (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1K54WGNoqmr4w4inGjprAd','tr','Kümes Hayvanları (taze)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1K54WGNoqmr4w4inGjprAd','zh','Poultry (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('1K54WGNoqmr4w4inGjprAd','freezer','freezer',90) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('1K54WGNoqmr4w4inGjprAd','fridge','fridge',6) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('1K54WGNoqmr4w4inGjprAd','zerodegreezone','zerodegreezone',7) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;

INSERT INTO foodgroups (cloud_id,bucket,owner_id,section,icon_name,position) VALUES ('6JgXf1Yywjj5iFAugd9yOm','ZWILLING',NULL,'Cereals','',0) ON CONFLICT(cloud_id) DO UPDATE SET section=excluded.section, icon_name=excluded.icon_name, position=excluded.position;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6JgXf1Yywjj5iFAugd9yOm','cs','Rice') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6JgXf1Yywjj5iFAugd9yOm','de','Reis') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6JgXf1Yywjj5iFAugd9yOm','en','Rice') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6JgXf1Yywjj5iFAugd9yOm','es','Arroz') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6JgXf1Yywjj5iFAugd9yOm','fr','Riz') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6JgXf1Yywjj5iFAugd9yOm','hu','Rice') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6JgXf1Yywjj5iFAugd9yOm','it','Riso') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6JgXf1Yywjj5iFAugd9yOm','ja','米') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6JgXf1Yywjj5iFAugd9yOm','ko','Rice') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6JgXf1Yywjj5iFAugd9yOm','nl','Rijst') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6JgXf1Yywjj5iFAugd9yOm','pl','Rice') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6JgXf1Yywjj5iFAugd9yOm','pt','Arroz') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6JgXf1Yywjj5iFAugd9yOm','sk','Rice') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6JgXf1Yywjj5iFAugd9yOm','tr','Pirinç') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6JgXf1Yywjj5iFAugd9yOm','zh','Rice') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('6JgXf1Yywjj5iFAugd9yOm','cupboard','cupboard',365) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;

INSERT INTO foodgroups (cloud_id,bucket,owner_id,section,icon_name,position) VALUES ('LKNSgQRfbQACF4huBHG0b','ZWILLING',NULL,'Cooked','',1) ON CONFLICT(cloud_id) DO UPDATE SET section=excluded.section, icon_name=excluded.icon_name, position=excluded.position;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('LKNSgQRfbQACF4huBHG0b','cs','Cooked Dishes') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('LKNSgQRfbQACF4huBHG0b','de','Gekochte Gerichte') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('LKNSgQRfbQACF4huBHG0b','en','Cooked Dishes') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('LKNSgQRfbQACF4huBHG0b','es','Platos preparados') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('LKNSgQRfbQACF4huBHG0b','fr','Plats cuits') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('LKNSgQRfbQACF4huBHG0b','hu','Cooked Dishes') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('LKNSgQRfbQACF4huBHG0b','it','Piatti cotti') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('LKNSgQRfbQACF4huBHG0b','ja','加熱した料理') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('LKNSgQRfbQACF4huBHG0b','ko','Cooked Dishes') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('LKNSgQRfbQACF4huBHG0b','nl','Gekookte Gerechten') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('LKNSgQRfbQACF4huBHG0b','pl','Cooked Dishes') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('LKNSgQRfbQACF4huBHG0b','pt','Pratos cozinhados') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('LKNSgQRfbQACF4huBHG0b','sk','Cooked Dishes') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('LKNSgQRfbQACF4huBHG0b','tr','Pişmiş Yemekler') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('LKNSgQRfbQACF4huBHG0b','zh','Cooked Dishes') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('LKNSgQRfbQACF4huBHG0b','freezer','freezer',35) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('LKNSgQRfbQACF4huBHG0b','fridge','fridge',7) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('LKNSgQRfbQACF4huBHG0b','zerodegreezone','zerodegreezone',9) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;

INSERT INTO foodgroups (cloud_id,bucket,owner_id,section,icon_name,position) VALUES ('7Ff9vmtaqsceHrXwfXsIo0','ZWILLING',NULL,'Vegetables & Fruits','',5) ON CONFLICT(cloud_id) DO UPDATE SET section=excluded.section, icon_name=excluded.icon_name, position=excluded.position;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7Ff9vmtaqsceHrXwfXsIo0','cs','Fruits (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7Ff9vmtaqsceHrXwfXsIo0','de','Früchte (frisch)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7Ff9vmtaqsceHrXwfXsIo0','en','Fruits (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7Ff9vmtaqsceHrXwfXsIo0','es','Fruta (fresca)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7Ff9vmtaqsceHrXwfXsIo0','fr','Fruits (frais)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7Ff9vmtaqsceHrXwfXsIo0','hu','Fruits (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7Ff9vmtaqsceHrXwfXsIo0','it','Frutta (fresca)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7Ff9vmtaqsceHrXwfXsIo0','ja','果物（生）') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7Ff9vmtaqsceHrXwfXsIo0','ko','Fruits (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7Ff9vmtaqsceHrXwfXsIo0','nl','Fruit (vers)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7Ff9vmtaqsceHrXwfXsIo0','pl','Fruits (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7Ff9vmtaqsceHrXwfXsIo0','pt','Frutas (frescas)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7Ff9vmtaqsceHrXwfXsIo0','sk','Fruits (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7Ff9vmtaqsceHrXwfXsIo0','tr','Meyve (taze)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('7Ff9vmtaqsceHrXwfXsIo0','zh','Fruits (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('7Ff9vmtaqsceHrXwfXsIo0','freezer','freezer',90) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('7Ff9vmtaqsceHrXwfXsIo0','fridge','fridge',10) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('7Ff9vmtaqsceHrXwfXsIo0','zerodegreezone','zerodegreezone',12) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;

INSERT INTO foodgroups (cloud_id,bucket,owner_id,section,icon_name,position) VALUES ('3FVUQxrT8qD1zgw1qlOrld','ZWILLING',NULL,'Fish & Seafood','zwillingRapier/Fish',6) ON CONFLICT(cloud_id) DO UPDATE SET section=excluded.section, icon_name=excluded.icon_name, position=excluded.position;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('3FVUQxrT8qD1zgw1qlOrld','cs','Fish (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('3FVUQxrT8qD1zgw1qlOrld','de','Fisch (frisch)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('3FVUQxrT8qD1zgw1qlOrld','en','Fish (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('3FVUQxrT8qD1zgw1qlOrld','es','Pescado (fresco)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('3FVUQxrT8qD1zgw1qlOrld','fr','Poisson (frais)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('3FVUQxrT8qD1zgw1qlOrld','hu','Fish (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('3FVUQxrT8qD1zgw1qlOrld','it','Pesce (fresco)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('3FVUQxrT8qD1zgw1qlOrld','ja','魚（生）') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('3FVUQxrT8qD1zgw1qlOrld','ko','Fish (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('3FVUQxrT8qD1zgw1qlOrld','nl','Vis (vers)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('3FVUQxrT8qD1zgw1qlOrld','pl','Fish (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('3FVUQxrT8qD1zgw1qlOrld','pt','Peixe (fresco)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('3FVUQxrT8qD1zgw1qlOrld','sk','Fish (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('3FVUQxrT8qD1zgw1qlOrld','tr','Balık (taze)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('3FVUQxrT8qD1zgw1qlOrld','zh','Fish (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('3FVUQxrT8qD1zgw1qlOrld','freezer','freezer',40) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('3FVUQxrT8qD1zgw1qlOrld','fridge','fridge',6) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('3FVUQxrT8qD1zgw1qlOrld','zerodegreezone','zerodegreezone',7) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;

INSERT INTO foodgroups (cloud_id,bucket,owner_id,section,icon_name,position) VALUES ('2NbvCmBeJouO4hGYVhWqYN','ZWILLING',NULL,'Meat','',10) ON CONFLICT(cloud_id) DO UPDATE SET section=excluded.section, icon_name=excluded.icon_name, position=excluded.position;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2NbvCmBeJouO4hGYVhWqYN','cs','Sausage (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2NbvCmBeJouO4hGYVhWqYN','de','Wurst (frisch)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2NbvCmBeJouO4hGYVhWqYN','en','Sausage (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2NbvCmBeJouO4hGYVhWqYN','es','Salchichas (fresco)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2NbvCmBeJouO4hGYVhWqYN','fr','Saucisse (fraîche)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2NbvCmBeJouO4hGYVhWqYN','hu','Sausage (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2NbvCmBeJouO4hGYVhWqYN','it','Salsiccia (fresca)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2NbvCmBeJouO4hGYVhWqYN','ja','ソーセージ（生）') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2NbvCmBeJouO4hGYVhWqYN','ko','Sausage (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2NbvCmBeJouO4hGYVhWqYN','nl','Worst (vers)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2NbvCmBeJouO4hGYVhWqYN','pl','Sausage (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2NbvCmBeJouO4hGYVhWqYN','pt','Salsicha (fresca)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2NbvCmBeJouO4hGYVhWqYN','sk','Sausage (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2NbvCmBeJouO4hGYVhWqYN','tr','Sosis (taze)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2NbvCmBeJouO4hGYVhWqYN','zh','Sausage (fresh)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('2NbvCmBeJouO4hGYVhWqYN','freezer','freezer',50) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('2NbvCmBeJouO4hGYVhWqYN','fridge','fridge',10) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('2NbvCmBeJouO4hGYVhWqYN','zerodegreezone','zerodegreezone',11) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;

INSERT INTO foodgroups (cloud_id,bucket,owner_id,section,icon_name,position) VALUES ('15gpHmQlIdWfDqMcLD5wGv','ZWILLING',NULL,'Cheese','zwillingRapier/HardCheese',11) ON CONFLICT(cloud_id) DO UPDATE SET section=excluded.section, icon_name=excluded.icon_name, position=excluded.position;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('15gpHmQlIdWfDqMcLD5wGv','cs','Hard cheese') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('15gpHmQlIdWfDqMcLD5wGv','de','Hartkäse') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('15gpHmQlIdWfDqMcLD5wGv','en','Hard cheese') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('15gpHmQlIdWfDqMcLD5wGv','es','Queso curado') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('15gpHmQlIdWfDqMcLD5wGv','fr','Fromage à pâte dure') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('15gpHmQlIdWfDqMcLD5wGv','hu','Hard cheese') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('15gpHmQlIdWfDqMcLD5wGv','it','Formaggio stagionato') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('15gpHmQlIdWfDqMcLD5wGv','ja','ハードチーズ') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('15gpHmQlIdWfDqMcLD5wGv','ko','Hard cheese') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('15gpHmQlIdWfDqMcLD5wGv','nl','Harde kaas') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('15gpHmQlIdWfDqMcLD5wGv','pl','Hard cheese') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('15gpHmQlIdWfDqMcLD5wGv','pt','Queijo duro') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('15gpHmQlIdWfDqMcLD5wGv','sk','Hard cheese') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('15gpHmQlIdWfDqMcLD5wGv','tr','Sert peynir') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('15gpHmQlIdWfDqMcLD5wGv','zh','Hard cheese') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('15gpHmQlIdWfDqMcLD5wGv','freezer','freezer',90) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('15gpHmQlIdWfDqMcLD5wGv','fridge','fridge',39) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('15gpHmQlIdWfDqMcLD5wGv','zerodegreezone','zerodegreezone',41) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;

INSERT INTO foodgroups (cloud_id,bucket,owner_id,section,icon_name,position) VALUES ('2cJg4UEsxXHJXu8ZEQLtBA','ZWILLING',NULL,'Cheese','',12) ON CONFLICT(cloud_id) DO UPDATE SET section=excluded.section, icon_name=excluded.icon_name, position=excluded.position;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2cJg4UEsxXHJXu8ZEQLtBA','cs','Soft cheese') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2cJg4UEsxXHJXu8ZEQLtBA','de','Weichkäse') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2cJg4UEsxXHJXu8ZEQLtBA','en','Soft cheese') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2cJg4UEsxXHJXu8ZEQLtBA','es','Queso tierno') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2cJg4UEsxXHJXu8ZEQLtBA','fr','Fromage à pâte molle') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2cJg4UEsxXHJXu8ZEQLtBA','hu','Soft cheese') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2cJg4UEsxXHJXu8ZEQLtBA','it','Formaggio fresco') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2cJg4UEsxXHJXu8ZEQLtBA','ja','ソフトチーズ') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2cJg4UEsxXHJXu8ZEQLtBA','ko','Soft cheese') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2cJg4UEsxXHJXu8ZEQLtBA','nl','Zachte kaas') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2cJg4UEsxXHJXu8ZEQLtBA','pl','Soft cheese') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2cJg4UEsxXHJXu8ZEQLtBA','pt','Queijo de pasta mole') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2cJg4UEsxXHJXu8ZEQLtBA','sk','Soft cheese') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2cJg4UEsxXHJXu8ZEQLtBA','tr','Yumuşak Peynir') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2cJg4UEsxXHJXu8ZEQLtBA','zh','Soft cheese') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('2cJg4UEsxXHJXu8ZEQLtBA','freezer','freezer',90) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('2cJg4UEsxXHJXu8ZEQLtBA','fridge','fridge',14) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('2cJg4UEsxXHJXu8ZEQLtBA','zerodegreezone','zerodegreezone',15) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;

INSERT INTO foodgroups (cloud_id,bucket,owner_id,section,icon_name,position) VALUES ('1eYaV78lo5EPxlMx4DHhJs','ZWILLING',NULL,'Baked Goods, Desserts & Snacks','',13) ON CONFLICT(cloud_id) DO UPDATE SET section=excluded.section, icon_name=excluded.icon_name, position=excluded.position;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1eYaV78lo5EPxlMx4DHhJs','cs','Desserts') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1eYaV78lo5EPxlMx4DHhJs','de','Dessert') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1eYaV78lo5EPxlMx4DHhJs','en','Desserts') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1eYaV78lo5EPxlMx4DHhJs','es','Postres') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1eYaV78lo5EPxlMx4DHhJs','fr','Desserts') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1eYaV78lo5EPxlMx4DHhJs','hu','Desserts') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1eYaV78lo5EPxlMx4DHhJs','it','Dolci') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1eYaV78lo5EPxlMx4DHhJs','ja','デザート') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1eYaV78lo5EPxlMx4DHhJs','ko','Desserts') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1eYaV78lo5EPxlMx4DHhJs','nl','Desserter') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1eYaV78lo5EPxlMx4DHhJs','pl','Desserts') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1eYaV78lo5EPxlMx4DHhJs','pt','Sobremesas') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1eYaV78lo5EPxlMx4DHhJs','sk','Desserts') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1eYaV78lo5EPxlMx4DHhJs','tr','Tatlılar') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('1eYaV78lo5EPxlMx4DHhJs','zh','Desserts') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('1eYaV78lo5EPxlMx4DHhJs','freezer','freezer',70) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('1eYaV78lo5EPxlMx4DHhJs','fridge','fridge',10) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('1eYaV78lo5EPxlMx4DHhJs','zerodegreezone','zerodegreezone',11) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;

INSERT INTO foodgroups (cloud_id,bucket,owner_id,section,icon_name,position) VALUES ('4MxgVIHuDJGfEzuZaUBE6H','ZWILLING',NULL,'Baked Goods, Desserts & Snacks','',14) ON CONFLICT(cloud_id) DO UPDATE SET section=excluded.section, icon_name=excluded.icon_name, position=excluded.position;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4MxgVIHuDJGfEzuZaUBE6H','cs','Bread') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4MxgVIHuDJGfEzuZaUBE6H','de','Brot') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4MxgVIHuDJGfEzuZaUBE6H','en','Bread') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4MxgVIHuDJGfEzuZaUBE6H','es','Pan') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4MxgVIHuDJGfEzuZaUBE6H','fr','Pain') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4MxgVIHuDJGfEzuZaUBE6H','hu','Bread') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4MxgVIHuDJGfEzuZaUBE6H','it','Pane') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4MxgVIHuDJGfEzuZaUBE6H','ja','パン') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4MxgVIHuDJGfEzuZaUBE6H','ko','Bread') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4MxgVIHuDJGfEzuZaUBE6H','nl','Brood') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4MxgVIHuDJGfEzuZaUBE6H','pl','Bread') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4MxgVIHuDJGfEzuZaUBE6H','pt','Pão') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4MxgVIHuDJGfEzuZaUBE6H','sk','Bread') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4MxgVIHuDJGfEzuZaUBE6H','tr','Ekmek') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('4MxgVIHuDJGfEzuZaUBE6H','zh','Bread') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('4MxgVIHuDJGfEzuZaUBE6H','cupboard','cupboard',8) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('4MxgVIHuDJGfEzuZaUBE6H','freezer','freezer',40) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;

INSERT INTO foodgroups (cloud_id,bucket,owner_id,section,icon_name,position) VALUES ('6W0JMg8GEYtFBpUEVS0JHs','ZWILLING',NULL,'Vegetables & Fruits','',15) ON CONFLICT(cloud_id) DO UPDATE SET section=excluded.section, icon_name=excluded.icon_name, position=excluded.position;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6W0JMg8GEYtFBpUEVS0JHs','cs','Legumes') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6W0JMg8GEYtFBpUEVS0JHs','de','Hülsenfrüchte') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6W0JMg8GEYtFBpUEVS0JHs','en','Legumes') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6W0JMg8GEYtFBpUEVS0JHs','es','Café y legumbres') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6W0JMg8GEYtFBpUEVS0JHs','fr','Café et légumineuses') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6W0JMg8GEYtFBpUEVS0JHs','hu','Legumes') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6W0JMg8GEYtFBpUEVS0JHs','it','Caffè e legumi') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6W0JMg8GEYtFBpUEVS0JHs','ja','コーヒー豆と豆類') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6W0JMg8GEYtFBpUEVS0JHs','ko','Legumes') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6W0JMg8GEYtFBpUEVS0JHs','nl','Koffiebonen en peulvruchten') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6W0JMg8GEYtFBpUEVS0JHs','pl','Legumes') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6W0JMg8GEYtFBpUEVS0JHs','pt','Grãos de café e leguminosas') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6W0JMg8GEYtFBpUEVS0JHs','sk','Legumes') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6W0JMg8GEYtFBpUEVS0JHs','tr','Kahve çekirdeği ve baklagiller') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('6W0JMg8GEYtFBpUEVS0JHs','zh','Legumes') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('6W0JMg8GEYtFBpUEVS0JHs','cupboard','cupboard',70) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;

INSERT INTO foodgroups (cloud_id,bucket,owner_id,section,icon_name,position) VALUES ('2q1XU1zQdIBeuYC1qdvDvC','ZWILLING',NULL,'Beverages & Drinks','zwillingRapier/Wine',16) ON CONFLICT(cloud_id) DO UPDATE SET section=excluded.section, icon_name=excluded.icon_name, position=excluded.position;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2q1XU1zQdIBeuYC1qdvDvC','cs','White wine (opened)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2q1XU1zQdIBeuYC1qdvDvC','de','Weißwein (geöffnet)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2q1XU1zQdIBeuYC1qdvDvC','en','White wine (opened)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2q1XU1zQdIBeuYC1qdvDvC','es','Vino blanco (abierto)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2q1XU1zQdIBeuYC1qdvDvC','fr','Vin blanc (ouvert)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2q1XU1zQdIBeuYC1qdvDvC','hu','White wine (opened)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2q1XU1zQdIBeuYC1qdvDvC','it','Vino bianco (aperto)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2q1XU1zQdIBeuYC1qdvDvC','ja','白ワイン') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2q1XU1zQdIBeuYC1qdvDvC','ko','White wine (opened)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2q1XU1zQdIBeuYC1qdvDvC','nl','Witte wijn (geopend)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2q1XU1zQdIBeuYC1qdvDvC','pl','White wine (opened)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2q1XU1zQdIBeuYC1qdvDvC','pt','Vinho branco (aberto)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2q1XU1zQdIBeuYC1qdvDvC','sk','White wine (opened)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2q1XU1zQdIBeuYC1qdvDvC','tr','Beyaz şarap (açılmış)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2q1XU1zQdIBeuYC1qdvDvC','zh','White wine (opened)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('2q1XU1zQdIBeuYC1qdvDvC','fridge','fridge',7) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;

INSERT INTO foodgroups (cloud_id,bucket,owner_id,section,icon_name,position) VALUES ('2e5MTa5nED9a9rQ32etff0','ZWILLING',NULL,'Beverages & Drinks','zwillingRapier/Wine',17) ON CONFLICT(cloud_id) DO UPDATE SET section=excluded.section, icon_name=excluded.icon_name, position=excluded.position;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2e5MTa5nED9a9rQ32etff0','cs','Red Wine (opened)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2e5MTa5nED9a9rQ32etff0','de','Rotwein (geöffnet)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2e5MTa5nED9a9rQ32etff0','en','Red Wine (opened)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2e5MTa5nED9a9rQ32etff0','es','Vino tinto (abierto)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2e5MTa5nED9a9rQ32etff0','fr','Vin rouge (ouvert)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2e5MTa5nED9a9rQ32etff0','hu','Red Wine (opened)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2e5MTa5nED9a9rQ32etff0','it','Vino rosso (aperto)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2e5MTa5nED9a9rQ32etff0','ja','赤ワイン') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2e5MTa5nED9a9rQ32etff0','ko','Red Wine (opened)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2e5MTa5nED9a9rQ32etff0','nl','Rode wijn (geopend)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2e5MTa5nED9a9rQ32etff0','pl','Red Wine (opened)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2e5MTa5nED9a9rQ32etff0','pt','Vinho tinto (aberto)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2e5MTa5nED9a9rQ32etff0','sk','Red Wine (opened)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2e5MTa5nED9a9rQ32etff0','tr','Kırmızı Şarap (açılmış)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_names (foodgroup_id,locale,name) VALUES ('2e5MTa5nED9a9rQ32etff0','zh','Red Wine (opened)') ON CONFLICT(foodgroup_id,locale) DO UPDATE SET name=excluded.name;
INSERT INTO foodgroup_storable (foodgroup_id,location,icon,days) VALUES ('2e5MTa5nED9a9rQ32etff0','cupboard','cupboard',7) ON CONFLICT(foodgroup_id,location) DO UPDATE SET icon=excluded.icon, days=excluded.days;

